### ISSUE TITLE
Many videos don’t show

### ISSUE THREAD

**Issue by kevincoleman** [meatspaces/meatspace-ios#7]
Seems intermittent.

http://cl.ly/image/0h0M1K0O253p
http://cl.ly/image/2O382M3y093P

Sometimes it seems to display/not based on position (3rd post up, first post up, etc.), and sometimes it seems to follow a particular post.

Happy to help test.

Thanks again for all the time making the app! Great work!

**Comment by marcusramberg** [comment]
It definitely happens after backgrounding the app. The cells get corrupted somehow, not sure if the avplayerlayer is removed or what. Any help on this issue would be most welcome.
